"""add fts search vector

Revision ID: bdcda636ebc1
Revises: 5799e87302c5
Create Date: 2026-07-26 22:55:12.742751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdcda636ebc1'
down_revision: Union[str, None] = '5799e87302c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_chunks_search_vector_gin', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_search_vector_gin', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'search_vector')
    # ### end Alembic commands ###
